version: '2'
services:
    tyk-redis:
        image: redis:latest
        container_name: tyk-redis
        hostname: redis
        ports:
            - "6379:6379"
        networks:
            gateway:
                aliases:
                    - redis
    tyk-mongo:
        image: mongo:latest
        container_name: tyk-mongo
        command: ["mongod", "--smallfiles"]
        hostname: mongo
        ports:
            - "27017:27017"
        networks:
            gateway:
                aliases:
                    - mongo

    tyk-dashboard:
        image: tykio/tyk-dashboard:v1.3
        container_name: tyk-dashboard
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./confs/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        networks:
            - gateway

    tyk-gateway:
        image: tykio/tyk-gateway:v2.4.0
        container_name: tyk-gateway
        ports:
            - "8181:8181"
        volumes:
            - ./confs/tyk.conf:/opt/tyk-gateway/tyk.conf
        networks:
            - gateway

    tyk-pump:
        image: tykio/tyk-pump-docker-pub:latest
        container_name: tyk-pump
        volumes:
            - ./confs/pump.conf:/opt/tyk-pump/pump.conf
        networks:
            - gateway

networks:
    gateway:
